### ISSUE TITLE
Webgl backend with wgsl shaders

### ISSUE THREAD

**Issue by madmaxio** [schell/renderling#20]
Hello, very interesting project, do you consider option for webgl backend and switching shaders fully to wgsl?

**Comment by schell** [comment]
Thank you for your interest! 

I'm using `wgpu` and do target WebGL2 when compiling for WASM. Unfortunately I don't think WebGL supports storage buffers, which this library relies on heavily for all the scenery (just about everything lives on the GPU). I'll have to figure out what I can do on web once I've proven the concept on desktop.

I considered writing the shaders in `wgsl` but it's been really fun writing them in Rust, even though there's more infrastructure needed to compile the shaders. Inevitably _some_ of the compute shaders will have to be in `wgsl` at least temporarily because `naga` (the shader translation layer for `wgpu`) doesn't support atomics in their SPIRV frontend. That's a bridge I haven't crossed yet, though I do have a very naive start on providing atomics [here](https://github.com/gfx-rs/naga/pull/2304). I'm currently working on gltf animation support and other rendering features like HDR and bloom.

**Comment by madmaxio** [comment]
I think wgsl is more like current standard for wgpu at the moment, that's why I ask. Haven't seen rust shaders as common approach, but will be interesting to see how this work in the future.
